on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/checkout@v2
      - name: Jest evaluator step
        id: test
        uses: betrybe/jest-evaluator-action@v2
        env:
          TEST_REPOSITORY_BRANCH: configure-automatic-tests
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v1
        with:
          evaluation-data: ${{ steps.test.outputs.result }}
          environment: staging
          pr-number: ${{ steps.test.outputs.pr-number }}